"""add connect with route and TS

Revision ID: 2d375e098584
Revises: ea00ebecf5f1
Create Date: 2024-05-24 11:52:46.519075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d375e098584'
down_revision: Union[str, None] = 'ea00ebecf5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('bs_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['bs_id'], ['bs.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planTime')
    op.add_column('route', sa.Column('ts_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'route', 'ts', ['ts_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_column('route', 'ts_id')
    op.create_table('planTime',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"planTime_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bs_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bs_id'], ['bs.id'], name='planTime_bs_id_fkey'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name='planTime_route_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='planTime_pkey')
    )
    op.drop_table('plan_time')
    # ### end Alembic commands ###
