"""Edit unique Values

Revision ID: 428d45fa3b9c
Revises: 2bb712c40d74
Create Date: 2024-06-06 20:17:00.164022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428d45fa3b9c'
down_revision: Union[str, None] = '2bb712c40d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bs', ['name'])
    op.create_unique_constraint(None, 'route', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route', type_='unique')
    op.drop_constraint(None, 'bs', type_='unique')
    # ### end Alembic commands ###
